spring:
  # mysql DB 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/birdmeal?serverTimezone=Asia/Seoul
    username: root
    password: hy1234

  # jpa 설정
  jpa:
    database: mysql
    show-sql: true  # jpa나 hibernate를 통해 CRUD를 실행하면 해당 CRUD의 sql을 로깅으로 보여준다
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect  # 각기 다른 DB에 맞는 SQL 문법을 처리
    hibernate:
      ddl-auto: update  # 서버를 실행할 때 마다 데이터 베이스 초기화 전략 : none ( 아무것도 설정 x , 초기값 )
    properties:
      hibernate:
        format_sql: true  # 로깅에 표시되는 sql을 보기 좋게 해준다


